name: CD

on:
  push:
    branches: [ main ]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run tests with timeout
      run: |
        echo "Starting tests..."
        timeout 60s npm test -- --verbose --detectOpenHandles
        if [ $? -eq 124 ]; then
          echo "Tests timed out after 60 seconds"
          exit 1
        elif [ $? -ne 0 ]; then
          echo "Tests failed"
          exit 1
        fi
      env:
        NODE_ENV: test
        CI: true
        DEBUG: 'express:*'
    
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          coverage/
          *.log
    
    - name: Deploy to production
      if: success()
      run: |
        echo "Deploying to production..."
        # Add your deployment commands here
        # For example:
        # npm run build
        # scp -r dist/* user@server:/path/to/deploy
      env:
        NODE_ENV: production
